### ISSUE TITLE
Sente Warning: Chsk is closed

### ISSUE THREAD

**Issue by tothda** [fulcrologic/fulcro-native-template#12]
Hi! I start all components, just as it was shown on the demo video. I can open the mobile app and it works fine, but I continuously get the following warnings from Sente. What do I wrong? Thanks!

<img width="559" alt="image" src="https://user-images.githubusercontent.com/7077/89109729-2c0aee80-d444-11ea-8226-4c4b8c03142f.png">

**Comment by gveres** [comment]
Just a note for anyone else running into this. What happens is that the app running in the simulator will try to establish a connection to a Fulcro Inspect instance through websockets. 
To resolve, either disable this behaviour, as stated in the readme: 

> By default native app will try to connect to Electron Fulcro Inspect. You may comment out the app.inspect-native-preload in shadow-cljs.edn to disable this.
--

or, simply run the Fulcro Inspector Electron app, available at https://github.com/fulcrologic/fulcro-inspect/releases , which will have the required websocket open, so not only the app stops complaining, you'll also have the Inspect superpowers at hand.
