### ISSUE TITLE
Unable to login with mobile client

### ISSUE THREAD

**Issue by slifin** [fulcrologic/fulcro-native-template#2]
I get this error when trying to log in on the mobile client, the web client appears to work correctly for logging in
<img src="https://i.imgur.com/yDfH3R6.png" />

I am using a real phone instead of the simulator, not sure if that makes a difference, in the meantime, I'm going to try and read around the state machine docs

**Comment by awkay** [comment]
If you're using a real phone you might have network connectivity issues...please use Slack clojurians #fulcro channel for discussion.
