### ISSUE TITLE
fulcro-inspect-electron won't work nicely for native

### ISSUE THREAD

**Issue by fjolne** [fulcrologic/fulcro-native-template#6]
Sente's WS channel type doesn't work in React Native environment, so it automatically downgrades to AJAX, causing a non-fatal error: https://github.com/ptaoussanis/sente/issues/361

Manually setting AJAX channel type removes the error, so if this param would customizable, we could enable Inspect by default for native. https://github.com/fulcrologic/fulcro/pull/366

**Comment by awkay** [comment]
Fixed Fulcro 3.1.8
